import type { ReferenceTemplateComponents } from "../../types";
import { FONTS, showcaseTheme } from "./theme";

export const showcaseLayout: ReferenceTemplateComponents = {
  topPanel: {
    visible: false,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    background: "transparent",
    radius: 0,
  },
  badgeRow: {
    visible: false,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    gap: 0,
  },
  status: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 24,
    fontWeight: 700,
    color: showcaseTheme.fc,
  },
  statusMiss: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 24,
    fontWeight: 700,
    color: "#FF5252",
  },
  statusSB: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 24,
    fontWeight: 700,
    color: "#FFA726",
  },
  starNotch: {
    visible: false,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    background: "transparent",
    radius: 0,
    tailColor: "transparent",
    iconColor: "transparent",
    statusColors: {},
    assets: {},
  },
  starRating: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 24,
    fontWeight: 700,
    color: "#FFFFFF",
  },
  pp: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 32,
    fontWeight: 700,
    color: "#FFFFFF",
  },

  // Primary Center Title: High-Contrast Showcase Typography
  mapTitle: {
    visible: true,
    x: 40,
    y: 240,
    width: 1200,
    height: 200,
    fontFamily: FONTS.default,
    fontSize: 148,
    fontWeight: 700,
    letterSpacing: 3,
    align: "center",
    valign: "center",
    textTransform: "uppercase",
    color: "#FFFFFF",
    gradient: "linear-gradient(180deg, #FFFFFF 0%, var(--accent-color, #00F0FF) 100%)",
    stroke: { width: 4, color: "var(--shadow-color, #06070C)" },
    extrusion: { depth: 6, offsetX: 1.5, offsetY: 2, color: "var(--shadow-color, #06070C)" },
    shadow: {
      offsetX: 0,
      offsetY: 18,
      blur: 32,
      color: "rgba(0, 0, 0, 0.85)",
    },
  },

  comboBadge: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.body,
    fontSize: 14,
    fontWeight: 700,
    color: "#FFFFFF",
    background: showcaseTheme.badgeBackground,
    borderColor: showcaseTheme.badgeBorder,
    borderWidth: 1,
    radius: 12,
  },
  difficultyBadge: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.body,
    fontSize: 14,
    fontWeight: 700,
    color: "#FFFFFF",
    background: showcaseTheme.badgeBackground,
    borderColor: showcaseTheme.badgeBorder,
    borderWidth: 1,
    radius: 12,
  },
  bpmBadge: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.body,
    fontSize: 14,
    fontWeight: 700,
    color: "#FFFFFF",
    background: showcaseTheme.badgeBackground,
    borderColor: showcaseTheme.badgeBorder,
    borderWidth: 1,
    radius: 12,
  },
  grade: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 32,
    fontWeight: 700,
    color: showcaseTheme.grade,
  },
  accuracy: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 24,
    fontWeight: 700,
    color: "#FFFFFF",
  },
  leaderboard: {
    visible: false,
    x: 0,
    y: 0,
    fontFamily: FONTS.default,
    fontSize: 24,
    fontWeight: 700,
    color: showcaseTheme.leaderboard,
  },
  avatar: {
    visible: false,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    radius: 0,
    objectFit: "cover",
  },
  countryFlag: {
    visible: false,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    radius: 0,
  },
  usernamePanel: {
    visible: false,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    fontFamily: FONTS.default,
    fontSize: 20,
    fontWeight: 700,
    color: "#FFFFFF",
    background: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    radius: 0,
  },
  modList: {
    visible: false,
    x: 0,
    y: 0,
    iconSize: 0,
    gap: 0,
    radius: 0,
    fallbackAcronyms: true,
  },
  twitchLogo: {
    visible: false,
    x: 0,
    y: 0,
    size: 0,
    radius: 0,
    asset: "",
    background: "transparent",
  },

  // Minimal Subtitle below Title
  bottomMessage: {
    visible: true,
    x: 40,
    y: 440,
    width: 1200,
    fontFamily: FONTS.default,
    fontSize: 28,
    fontWeight: 700,
    prefixColor: "#FFFFFF",
    highlightedColor: "var(--accent-color, #00F0FF)",
  },
};
