export type { OverlayBadge, OverlayData, OverlayMonthlyCount } from "../../shared/types/overlay";
import {
    LIFELINE_AVATAR,
    LIFELINE_BADGES,
    LIFELINE_BANNER,
    LIFELINE_MAPPER_AVATAR,
    LIFELINE_MAP_COVER,
    type OverlayData,
} from "../../shared/types/overlay";
export const DEFAULT_OVERLAY_DATA: OverlayData = {
    player: {
        username: "lifeline",
        flag: "🇮🇩",
        countryCode: "ID",
        crank: "- #1",
        grank: "#7",
        pp: "25 838pp",
        hours: 3664,
        playcount: 301395,
        badgeCount: LIFELINE_BADGES.length,
        badges: LIFELINE_BADGES,
        avatar: LIFELINE_AVATAR,
        banner: LIFELINE_BANNER,
        monthlyPlaycounts: [],
        peakMonth: "June 2020",
        peakCount: 7457,
    },
    map: {
        title: "I thought I was an angel [Fallen]",
        artist: "by Utsu-P",
        cover: LIFELINE_MAP_COVER,
        mapper: "-cy",
        mapperAvatar: LIFELINE_MAPPER_AVATAR,
        favs: "138",
        plays: "17 632",
        sr: "11.49",
        bpm: "300bpm",
        ar: 10.67,
        arMs: "349ms",
        od: 10.58,
        odMs: "16.5ms",
        cs: 4.0,
        hp: 4.5,
    },
};
