export type { OverlayBadge, OverlayData, OverlayMonthlyCount, OverlayScoreDetails, OverlayTopScore } from "../../shared/types/overlay";
import {
    LIFELINE_AVATAR,
    LIFELINE_BADGES,
    LIFELINE_BANNER,
    LIFELINE_MAPPER_AVATAR,
    LIFELINE_MAP_COVER,
    type OverlayData,
} from "../../shared/types/overlay";
export const DEFAULT_OVERLAY_DATA: OverlayData = {
    player: {
        username: "worst hr player",
        isSupporter: true,
        flag: "🇰🇷",
        countryCode: "KR",
        crank: "#4",
        grank: "#68",
        pp: "21 340pp",
        hours: 3664,
        playcount: 301395,
        badgeCount: LIFELINE_BADGES.length,
        badges: LIFELINE_BADGES,
        avatar: "https://a.ppy.sh/1415940",
        banner: LIFELINE_BANNER,
        monthlyPlaycounts: [],
        peakMonth: "June 2020",
        peakCount: 7457,
    },
    map: {
        title: "I thought I was an angel [Fallen]",
        artist: "by Utsu-P",
        cover: LIFELINE_MAP_COVER,
        mapper: "-cy",
        mapperAvatar: LIFELINE_MAPPER_AVATAR,
        favs: "138",
        plays: "17 632",
        sr: "8.53",
        bpm: "300bpm",
        ar: 9.70,
        arMs: "349ms",
        od: 9.70,
        odMs: "16.5ms",
        cs: 4.00,
        hp: 6.00,
        status: "ranked",
    },
    score: {
        totalScore: "80 109 230",
        combo: 1869,
        maxCombo: 1870,
        pp: "880PP",
        accuracy: "99.63%",
        rank: "S",
        count300: 8,
        count100: 0,
        count50: 0,
        countMiss: 0,
        playedAtAgo: "26 minutes ago",
        mods: ["HD", "HR"],
    },
    topScores: [
        { rank: "S", title: "Song That Might Play When You Fight Sans", mods: ["HD", "HR"], timeAgo: "1y", pp: "1146pp", cover: "https://assets.ppy.sh/beatmaps/1031435/covers/cover.jpg" },
        { rank: "X", title: "Bike Chase", mods: ["HD", "HR"], timeAgo: "1y", pp: "1120pp", cover: "https://assets.ppy.sh/beatmaps/1449830/covers/cover.jpg" },
        { rank: "S", title: "ANTIDOTE", mods: ["HD", "HR"], timeAgo: "1y", pp: "1108pp", cover: "https://assets.ppy.sh/beatmaps/1271616/covers/cover.jpg" },
        { rank: "S", title: "Bass Slut (Original Mix)", mods: ["HD", "DT"], timeAgo: "2y", pp: "1100pp", cover: "https://assets.ppy.sh/beatmaps/399358/covers/cover.jpg" },
        { rank: "S", title: "Last Goodbye", mods: ["HD", "HR"], timeAgo: "1y", pp: "1064pp", cover: "https://assets.ppy.sh/beatmaps/744372/covers/cover.jpg" },
        { rank: "A", title: "ChuChu Lovely MuniMuni MuraMura", mods: ["HD", "DT"], timeAgo: "1y", pp: "1058pp", cover: "https://assets.ppy.sh/beatmaps/847323/covers/cover.jpg" },
    ],
};
