import type { ReferenceTemplateComponents } from "../../types";
import { FONTS, referenceTheme as c } from "./theme";
const badgeDefaults = {
    visible: true,
    x: 0,
    y: 0,
    height: 66,
    autoWidth: true,
    fontFamily: FONTS.display,
    fontSize: 48,
    fontWeight: 600,
    color: c.text,
    align: "center",
    valign: "center",
    background: c.badgeBackground,
    borderColor: c.badgeBorder,
    borderWidth: 4,
} as const;
export const referenceLayout: ReferenceTemplateComponents = {
    topPanel: {
        visible: true,
        x: 14,
        y: 12,
        width: 1252,
        height: 244,
        background: "rgba(20, 14, 15, 0.25)",
        backgroundImage: {
            blur: 0,
            brightness: 0.78,
            saturation: 0.85,
            scale: 1.35,
            objectFit: "cover",
            objectPosition: "center top",
            overlayColor: "#141414",
            overlayOpacity: 0.22,
            overlayGradient: "180deg, rgba(20, 14, 15, 0.15) 0%, rgba(20, 14, 15, 0.42) 45%, rgba(20, 14, 15, 0.88) 100%",
            overlayGradientOpacity: 1,
        },
        borderColor: c.panelBorder,
        borderWidth: 4,
        radius: 26,
    },
    status: {
        visible: true,
        x: 112,
        y: 38,
        maxWidth: 300,
        fontFamily: FONTS.display,
        fontSize: 176,
        fontWeight: 600,
        color: c.fc,
        glow: { blur: 18, layers: 2 },
    },
    statusMiss: {
        visible: true,
        x: 112,
        y: 44,
        maxWidth: 300,
        fontFamily: FONTS.display,
        fontSize: 150,
        fontWeight: 700,
        color: "#FF355A",
        glow: { blur: 18, layers: 2 },
    },
    statusSB: {
        visible: true,
        x: 118,
        y: 158,
        fontFamily: FONTS.display,
        fontSize: 68,
        fontWeight: 700,
        color: "#B8B8B8",
        glow: { blur: 8, layers: 1 },
    },
    starNotch: {
        visible: true,
        x: 415,
        y: 12,
        width: 170,
        height: 86,
        assets: {
            ranked: "/assets/osu/notch/ranked.png",
            qualified: "/assets/osu/notch/approved.png",
            loved: "/assets/osu/notch/loved.png",
            approved: "/assets/osu/notch/approved.png",
            graveyard: "/assets/osu/notch/unranked.png",
            grave: "/assets/osu/notch/unranked.png",
            wip: "/assets/osu/notch/unranked.png",
            pending: "/assets/osu/notch/unranked.png",
            unranked: "/assets/osu/notch/unranked.png",
            unknown: "/assets/osu/notch/unranked.png",
        },
        statusColors: {
            ranked: "#3699F3",
            qualified: "#3EA551",
            loved: "#C3538F",
            approved: "#3EA551",
            graveyard: "#6D6C70",
            grave: "#6D6C70",
            wip: "#6D6C70",
            pending: "#6D6C70",
            unranked: "#6D6C70",
            unknown: "#6D6C70",
        },
        asset: "/assets/osu/notch/unranked.png",
        background: "#55A0D0",
        bottomColor: "#38719B",
        radius: 20,
        tailColor: c.starRating,
        iconColor: "#FFFFFF",
    },
    starRating: {
        visible: true,
        x: 598,
        y: 34,
        fontFamily: FONTS.display,
        fontSize: 84,
        fontWeight: 700,
        color: c.starRating,
        glow: { blur: 9, layers: 1 },
    },
    pp: {
        visible: true,
        x: 805,
        y: 40,
        width: 430,
        fontFamily: FONTS.display,
        fontSize: 124,
        fontWeight: 600,
        color: c.pp,
        align: "right",
        glow: { blur: 10, layers: 2 },
    },
    badgeRow: {
        visible: true,
        x: 38,
        y: 236,
        width: 1204,
        height: 66,
        gap: 24,
    },
    comboBadge: {
        ...badgeDefaults,
        width: 168,
        maxWidth: 300,
        paddingX: 26,
        radius: "33px 12px 12px 33px",
    },
    difficultyBadge: {
        ...badgeDefaults,
        width: 236,
        maxWidth: 560,
        textTransform: "uppercase",
        paddingX: 40,
        radius: 12,
    },
    bpmBadge: {
        ...badgeDefaults,
        width: 254,
        maxWidth: 300,
        paddingX: 28,
        radius: "12px 33px 33px 12px",
    },
    mapTitle: {
        visible: true,
        x: 140,
        y: 302,
        width: 1000,
        height: 122,
        maxWidth: 1000,
        fontFamily: FONTS.display,
        fontSize: 72,
        fontWeight: 600,
        color: c.text,
        align: "center",
        valign: "center",
        letterSpacing: 2,
    },
    grade: {
        visible: true,
        x: 82,
        y: 350,
        width: 205,
        maxWidth: 205,
        fontFamily: FONTS.display,
        fontSize: 288,
        fontWeight: 600,
        color: c.grade,
        glow: { blur: 18, layers: 2 },
    },
    accuracy: {
        visible: true,
        x: 300,
        y: 424,
        width: 230,
        fontFamily: FONTS.display,
        fontSize: 68,
        fontWeight: 600,
        color: c.text,
        align: "right",
        glow: { blur: 7, layers: 1 },
    },
    leaderboard: {
        visible: true,
        x: 380,
        y: 522,
        width: 150,
        fontFamily: FONTS.display,
        fontSize: 56,
        fontWeight: 600,
        color: c.leaderboard,
        align: "right",
        glow: { blur: 7, layers: 1 },
    },
    avatar: {
        visible: true,
        x: 566,
        y: 420,
        width: 152,
        height: 152,
        radius: 10,
        border: { color: "rgba(255, 255, 255, 0.15)", width: 2 },
        shadow: { x: 0, y: 4, blur: 14, color: "rgba(0, 0, 0, 0.45)" },
        objectFit: "cover",
    },
    countryFlag: {
        visible: true,
        x: 610,
        y: 552,
        width: 62,
        height: 42,
        radius: 6,
        border: { color: "rgba(255, 255, 255, 0.25)", width: 2 },
    },
    usernamePanel: {
        visible: true,
        x: 738,
        y: 418,
        width: 506,
        height: 82,
        fontFamily: FONTS.display,
        fontSize: 50,
        fontWeight: 600,
        color: c.text,
        align: "left",
        paddingX: 28,
        background: "linear-gradient(180deg, rgba(73, 64, 65, 0.85) 0%, rgba(50, 39, 40, 0.72) 100%)",
        borderColor: "transparent",
        borderWidth: 0,
        radius: 12,
        leftAccent: { color: "rgba(129, 124, 124, 0.85)", width: 14 },
    },
    modList: {
        visible: true,
        x: 750,
        y: 514,
        iconSize: 72,
        gap: -6,
        radius: 12,
        fallbackAcronyms: true,
        modColors: {
            HD: { bg: "#FFCC22", fg: "dark" },
            NC: { bg: "#7A5CFF", fg: "light" },
        },
    },
    twitchLogo: {
        visible: true,
        x: 28,
        y: 610,
        size: 94,
        radius: 20,
        asset: "/assets/twitch/twitch-glitch.svg",
        background: c.twitch,
    },
    bottomMessage: {
        visible: true,
        x: 140,
        y: 618,
        width: 1000,
        fontFamily: FONTS.display,
        fontSize: 64,
        fontWeight: 600,
        prefixColor: c.text,
        highlightedColor: c.accent,
        highlightedGlow: { color: "rgba(184, 184, 184, 0.5)", blur: 14, layers: 2 },
        letterSpacing: 1,
    },
};
