import type { ReferenceTemplateComponents } from "../../types";
import { FONTS, referenceTheme as c } from "./theme";

/**
 * Reference template layout in 1280x720 logical coordinates.
 * Derived from reference/Reference.png (1024x576) with x1.25 scaling, then tuned.
 * Every value here is safe to tweak programmatically.
 */
export const referenceLayout: ReferenceTemplateComponents = {
  topPanel: {
    visible: true,
    x: 14,
    y: 12,
    width: 1252,
    height: 244,
    // The bar carries its own zoomed crop of the artwork (backgroundImage
    // below), so the tint here stays light; the overall background is the
    // darker one (see template.background).
    background: "rgba(20, 14, 15, 0.25)",
    backgroundImage: {
      // Clear, top-anchored crop: the bar replicates the top of the artwork.
      blur: 0,
      brightness: 0.78,
      saturation: 0.85,
      scale: 1.35,
      objectFit: "cover",
      objectPosition: "center top",
      overlayColor: "#141414",
      overlayOpacity: 0.22,
      // Art fades into dark quickly so only the bar area stays light.
      overlayGradient: "180deg, rgba(20, 14, 15, 0.15) 0%, rgba(20, 14, 15, 0.42) 45%, rgba(20, 14, 15, 0.88) 100%",
      overlayGradientOpacity: 1,
    },
    borderColor: c.panelBorder,
    borderWidth: 4,
    radius: 26,
  },
  status: {
    visible: true,
    x: 112,
    y: 38,
    maxWidth: 300,
    fontFamily: FONTS.display,
    fontSize: 176,
    fontWeight: 600,
    color: c.fc,
    glow: { blur: 30, layers: 3 },
  },
  statusMiss: {
    visible: true,
    x: 112,
    y: 44,
    maxWidth: 300,
    fontFamily: FONTS.display,
    fontSize: 150,
    fontWeight: 700,
    color: "#FF355A",
    glow: { blur: 26, layers: 3 },
  },
  statusSB: {
    visible: true,
    x: 118,
    y: 158,
    fontFamily: FONTS.display,
    fontSize: 68,
    fontWeight: 700,
    color: "#FFFFFF",
    glow: { blur: 14, layers: 2 },
  },
  starNotch: {
    visible: true,
    x: 415,
    y: 12,
    width: 170,
    height: 86,
    // Per-status assets (icons baked in); unranked falls back to grayscale.
    assets: {
      ranked: "/assets/osu/notch/ranked.png",
      qualified: "/assets/osu/notch/ranked.png",
      loved: "/assets/osu/notch/loved.png",
      approved: "/assets/osu/notch/approved.png",
      grave: "/assets/osu/notch/unknown.png",
      unranked: "/assets/osu/notch/unknown.png",
    },
    // Star-rating colors sampled from the actual notch asset pixels.
    statusColors: {
      ranked: "#3699F3",
      qualified: "#3699F3",
      loved: "#C3538F",
      approved: "#3EA551",
      grave: "#6D6C70",
      unranked: "#6D6C70",
    },
    asset: "/assets/osu/notch/unranked.png",
    background: "#55A0D0",
    bottomColor: "#38719B",
    radius: 20,
    tailColor: c.starRating,
    iconColor: "#FFFFFF",
  },
  starRating: {
    visible: true,
    x: 598,
    y: 34,
    fontFamily: FONTS.display,
    fontSize: 84,
    fontWeight: 700,
    color: c.starRating,
    glow: { blur: 14, layers: 2 },
  },
  pp: {
    visible: true,
    x: 805,
    y: 40,
    width: 430,
    fontFamily: FONTS.display,
    fontSize: 124,
    fontWeight: 600,
    color: c.pp,
    align: "right",
    glow: { blur: 18, layers: 3 },
  },
  badgeRow: {
    visible: true,
    x: 38,
    y: 236,
    // Symmetric insets: 20px from the panel border on each side.
    width: 1204,
    height: 66,
    gap: 24,
  },
  comboBadge: {
    visible: true,
    x: 0,
    y: 0,
    width: 168,
    height: 66,
    autoWidth: true,
    maxWidth: 300,
    fontFamily: FONTS.display,
    fontSize: 48,
    fontWeight: 600,
    color: c.text,
    align: "center",
    valign: "center",
    paddingX: 26,
    background: c.badgeBackground,
    borderColor: c.badgeBorder,
    borderWidth: 4,
    // Pill outer corners, inner corners softened to match the DIFF badge.
    radius: "33px 12px 12px 33px",
  },
  difficultyBadge: {
    visible: true,
    x: 0,
    y: 0,
    width: 236,
    height: 66,
    autoWidth: true,
    maxWidth: 560,
    fontFamily: FONTS.display,
    fontSize: 48,
    fontWeight: 600,
    color: c.text,
    align: "center",
    valign: "center",
    textTransform: "uppercase",
    paddingX: 40,
    background: c.badgeBackground,
    borderColor: c.badgeBorder,
    borderWidth: 4,
    // Squarish, like the reference design.
    radius: 12,
  },
  bpmBadge: {
    visible: true,
    x: 0,
    y: 0,
    width: 254,
    height: 66,
    autoWidth: true,
    maxWidth: 300,
    fontFamily: FONTS.display,
    fontSize: 48,
    fontWeight: 600,
    color: c.text,
    align: "center",
    valign: "center",
    paddingX: 28,
    background: c.badgeBackground,
    borderColor: c.badgeBorder,
    borderWidth: 4,
    // Pill outer corners, inner corners softened to match the DIFF badge.
    radius: "12px 33px 33px 12px",
  },
  mapTitle: {
    visible: true,
    x: 140,
    y: 330,
    width: 1000,
    maxWidth: 1000,
    fontFamily: FONTS.display,
    fontSize: 72,
    fontWeight: 600,
    color: c.text,
    align: "center",
    letterSpacing: 2,
  },
  grade: {
    visible: true,
    x: 82,
    y: 350,
    fontFamily: FONTS.display,
    fontSize: 288,
    fontWeight: 600,
    color: c.grade,
    glow: { blur: 30, layers: 3 },
  },
  accuracy: {
    visible: true,
    x: 300,
    y: 424,
    width: 230,
    fontFamily: FONTS.display,
    fontSize: 68,
    fontWeight: 600,
    color: c.text,
    align: "right",
    glow: { blur: 12, layers: 2 },
  },
  leaderboard: {
    visible: true,
    x: 380,
    y: 522,
    width: 150,
    fontFamily: FONTS.display,
    fontSize: 56,
    fontWeight: 600,
    color: c.leaderboard,
    align: "right",
    glow: { blur: 12, layers: 2 },
  },
  avatar: {
    visible: true,
    x: 566,
    y: 420,
    width: 152,
    height: 152,
    radius: 10,
    border: { color: "rgba(255, 255, 255, 0.15)", width: 2 },
    shadow: { x: 0, y: 4, blur: 14, color: "rgba(0, 0, 0, 0.45)" },
    objectFit: "cover",
  },
  countryFlag: {
    visible: true,
    x: 610,
    y: 552,
    width: 62,
    height: 42,
    radius: 6,
    border: { color: "rgba(255, 255, 255, 0.25)", width: 2 },
  },
  usernamePanel: {
    visible: true,
    x: 738,
    y: 418,
    width: 506,
    height: 82,
    fontFamily: FONTS.display,
    fontSize: 50,
    fontWeight: 600,
    color: c.text,
    align: "left",
    paddingX: 28,
    background: "linear-gradient(180deg, rgba(73, 64, 65, 0.85) 0%, rgba(50, 39, 40, 0.72) 100%)",
    borderColor: "transparent",
    borderWidth: 0,
    radius: 12,
    leftAccent: { color: "rgba(129, 124, 124, 0.85)", width: 14 },
  },
  modList: {
    visible: true,
    x: 750,
    y: 514,
    iconSize: 72,
    gap: -6, // slight overlap, like the reference
    radius: 12,
    fallbackAcronyms: true,
    // Matches the reference: yellow HD tile, purple NC tile.
    modColors: {
      HD: { bg: "#FFCC22", fg: "dark" },
      NC: { bg: "#7A5CFF", fg: "light" },
    },
  },
  twitchLogo: {
    visible: true,
    x: 28,
    y: 610,
    size: 94,
    radius: 20,
    asset: "/assets/twitch/twitch-glitch.svg",
    background: c.twitch,
  },
  bottomMessage: {
    visible: true,
    x: 140,
    y: 618,
    width: 1000,
    fontFamily: FONTS.display,
    fontSize: 64,
    fontWeight: 600,
    prefixColor: c.text,
    highlightedColor: c.accent,
    highlightedGlow: { color: "rgba(184, 184, 184, 0.5)", blur: 14, layers: 2 },
    letterSpacing: 1,
  },
};
