import type { ReferenceTemplateComponents } from "../../types";
import { FONTS, adaptableTheme } from "./theme";
export const adaptableLayout: ReferenceTemplateComponents = {
    topPanel: {
        visible: false,
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        background: "transparent",
        radius: 0,
    },
    badgeRow: {
        visible: false,
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        gap: 0,
    },
    status: {
        visible: true,
        x: 52,
        y: 350,
        fontFamily: FONTS.display,
        fontSize: 32,
        fontWeight: 700,
        color: adaptableTheme.fc,
        align: "left",
        background: "rgba(18, 24, 20, 0.8)",
        border: `2px solid ${adaptableTheme.fc}`,
        borderRadius: 16,
        padding: "6px 20px",
        boxShadow: `0 4px 18px rgba(0, 0, 0, 0.4), 0 0 16px ${adaptableTheme.fc}55`,
    },
    statusMiss: {
        visible: true,
        x: 52,
        y: 350,
        fontFamily: FONTS.display,
        fontSize: 32,
        fontWeight: 700,
        color: "#FF5252",
        align: "left",
        background: "rgba(30, 18, 20, 0.8)",
        border: "2px solid #FF5252",
        borderRadius: 16,
        padding: "6px 20px",
        boxShadow: "0 4px 18px rgba(0, 0, 0, 0.4), 0 0 14px rgba(255, 82, 82, 0.4)",
    },
    statusSB: {
        visible: true,
        x: 210,
        y: 350,
        fontFamily: FONTS.display,
        fontSize: 32,
        fontWeight: 700,
        color: "#FFA726",
        align: "left",
        background: "rgba(30, 24, 18, 0.8)",
        border: "2px solid #FFA726",
        borderRadius: 16,
        padding: "6px 20px",
        boxShadow: "0 4px 18px rgba(0, 0, 0, 0.4), 0 0 14px rgba(255, 167, 38, 0.4)",
    },
    starNotch: {
        visible: false,
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        background: "transparent",
        radius: 0,
        tailColor: "transparent",
        iconColor: "transparent",
        statusColors: {},
        assets: {},
    },
    starRating: {
        visible: true,
        x: 1080,
        y: 40,
        fontFamily: FONTS.display,
        fontSize: 24,
        fontWeight: 700,
        color: "#FFFDF9",
        background: "rgba(18, 24, 20, 0.8)",
        border: "2px solid #FFD166",
        borderRadius: 18,
        padding: "6px 20px",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.35), 0 0 14px rgba(255, 209, 102, 0.4)",
    },
    pp: {
        visible: true,
        x: 52,
        y: 420,
        fontFamily: FONTS.display,
        fontSize: 112,
        fontWeight: 700,
        letterSpacing: 1,
        color: adaptableTheme.accent,
        gradient: "linear-gradient(180deg, #FFEAA7 0%, #55E6C1 50%, #10AC84 100%)",
        stroke: { width: 3.5, color: "#101612" },
        shadow: {
            offsetX: -4,
            offsetY: 8,
            blur: 0,
            color: "rgba(10, 15, 12, 0.95)",
        },
        glow: {
            color: adaptableTheme.accent,
            blur: 24,
            layers: 2,
        },
    },
    mapTitle: {
        visible: true,
        x: 52,
        y: 540,
        width: 1176,
        height: 90,
        fontFamily: FONTS.display,
        fontSize: 68,
        fontWeight: 700,
        letterSpacing: 1,
        color: "#FFFFFF",
        gradient: "linear-gradient(180deg, #FFFFFF 0%, #E8EEEA 50%, #B8C8BC 100%)",
        stroke: { width: 3, color: "#101612" },
        shadow: {
            offsetX: -4,
            offsetY: 8,
            blur: 0,
            color: "rgba(10, 15, 12, 0.95)",
        },
    },
    comboBadge: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.body,
        fontSize: 14,
        fontWeight: 700,
        color: "#FFFFFF",
        background: adaptableTheme.badgeBackground,
        borderColor: adaptableTheme.badgeBorder,
        borderWidth: 1,
        radius: 12,
    },
    difficultyBadge: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.body,
        fontSize: 14,
        fontWeight: 700,
        color: "#FFFFFF",
        background: adaptableTheme.badgeBackground,
        borderColor: adaptableTheme.badgeBorder,
        borderWidth: 1,
        radius: 12,
    },
    bpmBadge: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.body,
        fontSize: 14,
        fontWeight: 700,
        color: "#FFFFFF",
        background: adaptableTheme.badgeBackground,
        borderColor: adaptableTheme.badgeBorder,
        borderWidth: 1,
        radius: 12,
    },
    grade: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.display,
        fontSize: 32,
        fontWeight: 700,
        color: adaptableTheme.grade,
    },
    accuracy: {
        visible: true,
        x: 52,
        y: 642,
        fontFamily: FONTS.display,
        fontSize: 24,
        fontWeight: 700,
        color: "#FFFFFF",
        background: "rgba(18, 24, 20, 0.8)",
        border: "2px solid rgba(255, 255, 255, 0.35)",
        borderRadius: 16,
        padding: "6px 20px",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.35)",
    },
    leaderboard: {
        visible: true,
        x: 236,
        y: 642,
        fontFamily: FONTS.display,
        fontSize: 24,
        fontWeight: 700,
        color: adaptableTheme.leaderboard,
        background: "rgba(18, 24, 20, 0.8)",
        border: `2px solid ${adaptableTheme.leaderboard}`,
        borderRadius: 16,
        padding: "6px 18px",
        boxShadow: `0 4px 16px rgba(0, 0, 0, 0.35), 0 0 12px ${adaptableTheme.leaderboard}55`,
    },
    avatar: {
        visible: true,
        x: 52,
        y: 40,
        width: 60,
        height: 60,
        radius: 30,
        objectFit: "cover",
        border: { color: adaptableTheme.accent, width: 2.5 },
        shadow: { x: 0, y: 4, blur: 12, color: "rgba(0,0,0,0.4)" },
    },
    countryFlag: {
        visible: true,
        x: 124,
        y: 48,
        width: 30,
        height: 20,
        radius: 4,
    },
    usernamePanel: {
        visible: true,
        x: 164,
        y: 42,
        width: 240,
        height: 32,
        fontFamily: FONTS.display,
        fontSize: 20,
        fontWeight: 700,
        color: "#FFFFFF",
        background: "rgba(18, 24, 20, 0.8)",
        borderColor: "rgba(255, 255, 255, 0.3)",
        borderWidth: 1.5,
        radius: 16,
        paddingX: 14,
    },
    modList: {
        visible: true,
        x: 124,
        y: 74,
        iconSize: 26,
        gap: 6,
        radius: 6,
        fallbackAcronyms: true,
    },
    twitchLogo: {
        visible: false,
        x: 1200,
        y: 40,
        size: 32,
        radius: 8,
        asset: "/assets/twitch/twitch-glitch.svg",
        background: "transparent",
    },
    bottomMessage: {
        visible: false,
        x: 52,
        y: 670,
        width: 1176,
        fontFamily: FONTS.display,
        fontSize: 18,
        fontWeight: 600,
        prefixColor: "#FFFFFF",
        highlightedColor: adaptableTheme.accent,
    },
    innerBorder: {
        visible: true,
        x: 24,
        y: 24,
        inset: 24,
        border: "2.5px solid rgba(255, 255, 255, 0.45)",
        borderRadius: 18,
    },
};
