import type { ReferenceTemplateComponents } from "../../types";
import { FONTS, cuteTheme } from "./theme";
export const cuteLayout: ReferenceTemplateComponents = {
    topPanel: {
        visible: false,
        x: 24,
        y: 20,
        width: 1232,
        height: 72,
        background: "rgba(25, 18, 34, 0.45)",
        borderColor: "rgba(255, 255, 255, 0.25)",
        borderWidth: 1.5,
        radius: 24,
    },
    badgeRow: {
        visible: false,
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        gap: 0,
    },
    status: {
        visible: true,
        x: 48,
        y: 375,
        fontFamily: FONTS.display,
        fontSize: 34,
        fontWeight: 700,
        color: cuteTheme.fc,
        align: "left",
        background: "rgba(26, 18, 34, 0.78)",
        border: `2px solid ${cuteTheme.fc}`,
        borderRadius: 18,
        padding: "6px 22px",
        boxShadow: `0 4px 20px rgba(0, 0, 0, 0.35), 0 0 16px ${cuteTheme.fc}55`,
    },
    statusMiss: {
        visible: true,
        x: 48,
        y: 375,
        fontFamily: FONTS.display,
        fontSize: 34,
        fontWeight: 700,
        color: "#FF5252",
        align: "left",
        background: "rgba(34, 18, 24, 0.78)",
        border: "2px solid #FF5252",
        borderRadius: 18,
        padding: "6px 22px",
        boxShadow: "0 4px 20px rgba(0, 0, 0, 0.35), 0 0 16px rgba(255, 82, 82, 0.4)",
    },
    statusSB: {
        visible: true,
        x: 210,
        y: 375,
        fontFamily: FONTS.display,
        fontSize: 34,
        fontWeight: 700,
        color: "#FFA726",
        align: "left",
        background: "rgba(34, 25, 18, 0.78)",
        border: "2px solid #FFA726",
        borderRadius: 18,
        padding: "6px 20px",
        boxShadow: "0 4px 20px rgba(0, 0, 0, 0.35), 0 0 14px rgba(255, 167, 38, 0.4)",
    },
    starNotch: {
        visible: false,
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        background: "transparent",
        radius: 0,
        tailColor: "transparent",
        iconColor: "transparent",
        statusColors: {},
        assets: {},
    },
    starRating: {
        visible: true,
        x: 1100,
        y: 34,
        fontFamily: FONTS.display,
        fontSize: 24,
        fontWeight: 700,
        color: "#FFFDF9",
        background: "rgba(25, 18, 34, 0.78)",
        border: "2px solid #FFD166",
        borderRadius: 18,
        padding: "6px 18px",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.3), 0 0 12px rgba(255, 209, 102, 0.4)",
    },
    pp: {
        visible: true,
        x: 48,
        y: 440,
        fontFamily: FONTS.display,
        fontSize: 116,
        fontWeight: 700,
        letterSpacing: 1,
        color: "#FFFFFF",
        gradient: "linear-gradient(180deg, #FFFFFF 0%, #FFF2F5 60%, #FFDCE5 100%)",
        shadow: {
            offsetX: 0,
            offsetY: 8,
            blur: 24,
            color: "rgba(15, 10, 22, 0.65)",
        },
        glow: {
            color: cuteTheme.accent,
            blur: 26,
            layers: 2,
        },
    },
    mapTitle: {
        visible: true,
        x: 48,
        y: 636,
        width: 1184,
        height: 48,
        fontFamily: FONTS.display,
        fontSize: 26,
        fontWeight: 600,
        color: "#FFFFFF",
        background: "rgba(22, 16, 30, 0.75)",
        border: "1.5px solid rgba(255, 255, 255, 0.25)",
        borderRadius: 24,
        padding: "8px 24px",
        boxShadow: "0 6px 24px rgba(0, 0, 0, 0.4)",
    },
    comboBadge: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.body,
        fontSize: 14,
        fontWeight: 700,
        color: "#FFFFFF",
        background: cuteTheme.badgeBackground,
        borderColor: cuteTheme.badgeBorder,
        borderWidth: 1,
        radius: 12,
    },
    difficultyBadge: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.body,
        fontSize: 14,
        fontWeight: 700,
        color: "#FFFFFF",
        background: cuteTheme.badgeBackground,
        borderColor: cuteTheme.badgeBorder,
        borderWidth: 1,
        radius: 12,
    },
    bpmBadge: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.body,
        fontSize: 14,
        fontWeight: 700,
        color: "#FFFFFF",
        background: cuteTheme.badgeBackground,
        borderColor: cuteTheme.badgeBorder,
        borderWidth: 1,
        radius: 12,
    },
    grade: {
        visible: false,
        x: 0,
        y: 0,
        fontFamily: FONTS.display,
        fontSize: 32,
        fontWeight: 700,
        color: cuteTheme.grade,
    },
    accuracy: {
        visible: true,
        x: 48,
        y: 574,
        fontFamily: FONTS.display,
        fontSize: 26,
        fontWeight: 700,
        color: "#FFFFFF",
        background: "rgba(22, 16, 30, 0.78)",
        border: "2px solid rgba(255, 255, 255, 0.35)",
        borderRadius: 16,
        padding: "6px 20px",
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.35)",
    },
    leaderboard: {
        visible: true,
        x: 236,
        y: 574,
        fontFamily: FONTS.display,
        fontSize: 26,
        fontWeight: 700,
        color: cuteTheme.leaderboard,
        background: "rgba(22, 16, 30, 0.78)",
        border: `2px solid ${cuteTheme.leaderboard}`,
        borderRadius: 16,
        padding: "6px 18px",
        boxShadow: `0 4px 16px rgba(0, 0, 0, 0.35), 0 0 12px ${cuteTheme.leaderboard}55`,
    },
    avatar: {
        visible: true,
        x: 48,
        y: 34,
        width: 60,
        height: 60,
        radius: 30,
        objectFit: "cover",
        border: { color: cuteTheme.accent, width: 2.5 },
        shadow: { x: 0, y: 4, blur: 12, color: "rgba(0,0,0,0.4)" },
    },
    countryFlag: {
        visible: true,
        x: 120,
        y: 42,
        width: 30,
        height: 20,
        radius: 4,
    },
    usernamePanel: {
        visible: true,
        x: 160,
        y: 36,
        width: 240,
        height: 32,
        fontFamily: FONTS.display,
        fontSize: 22,
        fontWeight: 700,
        color: "#FFFFFF",
        background: "rgba(25, 18, 34, 0.78)",
        borderColor: "rgba(255, 255, 255, 0.25)",
        borderWidth: 1.5,
        radius: 16,
        paddingX: 14,
    },
    modList: {
        visible: true,
        x: 120,
        y: 68,
        iconSize: 26,
        gap: 6,
        radius: 6,
        fallbackAcronyms: true,
    },
    twitchLogo: {
        visible: false,
        x: 1200,
        y: 34,
        size: 32,
        radius: 8,
        asset: "/assets/twitch/twitch-glitch.svg",
        background: "transparent",
    },
    bottomMessage: {
        visible: false,
        x: 48,
        y: 670,
        width: 1184,
        fontFamily: FONTS.display,
        fontSize: 18,
        fontWeight: 600,
        prefixColor: "#FFFFFF",
        highlightedColor: cuteTheme.accent,
    },
    sparkles: {
        visible: true,
        x: 0,
        y: 0,
        color: cuteTheme.accent,
    },
    innerBorder: {
        visible: true,
        x: 18,
        y: 18,
        inset: 18,
        border: "2px solid rgba(255, 255, 255, 0.32)",
        borderRadius: 22,
    },
};
