import type { ReferenceTemplateComponents } from "../../types";
import { FONTS, cuteTheme } from "./theme";

const badgeDefaults = {
    visible: true,
    x: 0,
    y: 0,
    fontFamily: FONTS.body,
    fontSize: 40,
    fontWeight: 700,
    color: "#FFFFFF",
    background: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    radius: 0,
} as const;
export const cuteLayout: ReferenceTemplateComponents = {
    topPanel: {
        visible: true,
        x: 30,
        y: 185,
        width: 1220,
        height: 275,
        background: "rgba(10, 8, 14, 0.42)",
        borderColor: "rgba(184, 184, 184, 0.45)",
        borderWidth: 1.5,
        radius: 24,
        backdropBlur: 10,
        shadow: { x: 0, y: 8, blur: 30, color: "rgba(0, 0, 0, 0.3)" },
    },
    badgeRow: {
        visible: true,
        x: 60,
        y: 612,
        width: 1160,
        height: 48,
        gap: 32,
    },
    status: {
        visible: true,
        x: 930,
        y: 185,
        width: 260,
        maxWidth: 260,
        height: 275,
        valign: "center",
        fontFamily: FONTS.display,
        fontSize: 158,
        fontWeight: 700,
        color: cuteTheme.fc,
        align: "center",
        glow: { color: cuteTheme.fc, blur: 12, layers: 1 },
    },
    statusMiss: {
        visible: true,
        x: 930,
        y: 185,
        width: 260,
        maxWidth: 260,
        height: 275,
        valign: "center",
        fontFamily: FONTS.display,
        fontSize: 158,
        fontWeight: 700,
        color: "#FF5252",
        align: "center",
        glow: { color: "#FF5252", blur: 12, layers: 1 },
    },
    statusSB: {
        visible: true,
        x: 930,
        y: 185,
        width: 260,
        maxWidth: 260,
        height: 275,
        valign: "center",
        fontFamily: FONTS.display,
        fontSize: 120,
        fontWeight: 700,
        color: "#FFFFFF",
        align: "center",
        glow: { color: "rgba(255, 255, 255, 0.65)", blur: 9, layers: 1 },
    },
    starNotch: {
        visible: true,
        x: 555,
        y: 0,
        width: 170,
        height: 86,
        assets: {
            ranked: "/assets/osu/notch/ranked.png",
            qualified: "/assets/osu/notch/approved.png",
            loved: "/assets/osu/notch/loved.png",
            approved: "/assets/osu/notch/approved.png",
            graveyard: "/assets/osu/notch/unranked.png",
            grave: "/assets/osu/notch/unranked.png",
            wip: "/assets/osu/notch/unranked.png",
            pending: "/assets/osu/notch/unranked.png",
            unranked: "/assets/osu/notch/unranked.png",
            unknown: "/assets/osu/notch/unranked.png",
        },
        statusColors: {},
        asset: "/assets/osu/notch/unranked.png",
        background: "#55A0D0",
        bottomColor: "#38719B",
        radius: 20,
        tailColor: cuteTheme.starRating,
        iconColor: "#FFFFFF",
    },
    starRating: {
        visible: true,
        x: 500,
        y: 98,
        width: 280,
        maxWidth: 280,
        fontFamily: FONTS.display,
        fontSize: 73,
        fontWeight: 700,
        color: "#FFD166",
        align: "center",
        glow: { color: "#FFD166", blur: 9, layers: 1 },
    },
    pp: {
        visible: true,
        x: 360,
        y: 185,
        width: 560,
        maxWidth: 560,
        height: 275,
        valign: "center",
        fontFamily: FONTS.display,
        fontSize: 130,
        fontWeight: 700,
        letterSpacing: 1,
        color: "#FFFFFF",
        align: "center",
        shadow: {
            offsetX: 0,
            offsetY: 6,
            blur: 16,
            color: "rgba(15, 10, 22, 0.65)",
        },
        glow: {
            color: cuteTheme.accent,
            blur: 14,
            layers: 2,
        },
    },
    mapArtist: {
        visible: true,
        x: 350,
        y: 480,
        width: 580,
        maxWidth: 580,
        fontFamily: FONTS.display,
        fontSize: 38,
        fontWeight: 600,
        color: "#C8C3CC",
        align: "center",
        shadow: { offsetX: 0, offsetY: 3, blur: 8, color: "rgba(0, 0, 0, 0.8)" },
    },
    mapTitle: {
        visible: true,
        x: 60,
        y: 525,
        width: 1160,
        maxWidth: 1160,
        height: 72,
        fontFamily: FONTS.display,
        fontSize: 58,
        fontWeight: 700,
        lineHeight: 1,
        color: "#FFFFFF",
        align: "center",
        shadow: { offsetX: 0, offsetY: 4, blur: 10, color: "rgba(0, 0, 0, 0.75)" },
    },
    comboBadge: {
        ...badgeDefaults,
        width: 200,
        align: "left",
    },
    difficultyBadge: {
        ...badgeDefaults,
        width: 600,
        align: "center",
        textTransform: "uppercase",
    },
    bpmBadge: {
        ...badgeDefaults,
        width: 200,
        align: "right",
    },
    grade: {
        visible: true,
        x: 70,
        y: 185,
        width: 280,
        maxWidth: 280,
        height: 275,
        valign: "center",
        fontFamily: FONTS.display,
        fontSize: 190,
        fontWeight: 700,
        color: cuteTheme.grade,
        align: "center",
    },
    accuracy: {
        visible: true,
        x: 960,
        y: 112,
        width: 260,
        maxWidth: 260,
        fontFamily: FONTS.display,
        fontSize: 62,
        fontWeight: 700,
        color: "#FFFFFF",
        align: "right",
        glow: { color: "rgba(255, 101, 132, 0.5)", blur: 8, layers: 1 },
    },
    leaderboard: {
        visible: true,
        x: 960,
        y: 66,
        width: 260,
        maxWidth: 260,
        fontFamily: FONTS.display,
        fontSize: 40,
        fontWeight: 700,
        color: cuteTheme.leaderboard,
        align: "right",
        glow: { color: cuteTheme.leaderboard, blur: 7, layers: 1 },
    },
    avatar: {
        visible: true,
        x: 60,
        y: 52,
        width: 120,
        height: 120,
        radius: 24,
        objectFit: "cover",
        border: { color: cuteTheme.accent, width: 2.5 },
        shadow: { x: 0, y: 4, blur: 12, color: "rgba(0,0,0,0.4)" },
    },
    countryFlag: {
        visible: true,
        x: 140,
        y: 143,
        width: 40,
        height: 27,
        radius: 5,
        border: { color: "rgba(255, 255, 255, 0.4)", width: 2 },
    },
    usernamePanel: {
        visible: true,
        x: 200,
        y: 60,
        width: 390,
        height: 64,
        fontFamily: FONTS.display,
        fontSize: 48,
        fontWeight: 700,
        color: "#FFFFFF",
        align: "left",
        background: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        radius: 0,
        paddingX: 0,
    },
    modList: {
        visible: true,
        x: 200,
        y: 128,
        iconSize: 38,
        gap: 4,
        radius: 7,
        fallbackAcronyms: true,
    },
    twitchLogo: {
        visible: false,
        x: 1200,
        y: 34,
        size: 32,
        radius: 8,
        asset: "/assets/twitch/twitch-glitch.svg",
        background: "transparent",
    },
    bottomMessage: {
        visible: false,
        x: 48,
        y: 670,
        width: 1184,
        fontFamily: FONTS.display,
        fontSize: 18,
        fontWeight: 600,
        prefixColor: "#FFFFFF",
        highlightedColor: cuteTheme.accent,
    },
    sparkles: {
        visible: false,
        x: 0,
        y: 0,
        color: cuteTheme.accent,
        opacity: 0.55,
    },
    innerBorder: {
        visible: false,
        x: 18,
        y: 18,
        inset: 30,
        border: "1.5px solid rgba(255, 255, 255, 0.32)",
        borderRadius: 24,
    },
};
